nav:
  logo:
  display_title: true
  display_post_title: true
  fixed: true

menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive

social:
  fab fa-github: https://github.com/gitfdy || Github || '#24292e'

index_img:

default_top_img:

footer:
  owner:
    enable: true
    since: 2026
  custom_text: gitfdy 的博客

post_meta:
  date_type: both

translate:
  enable: false

local_search:
  enable: true
  preload: false
